<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Click_07_BankTransfer</name>
   <tag></tag>
   <elementGuidId>252ae50f-164e-428b-b62c-b551f012dc87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/section/div[6]/div[3]/div/ul/li[6]/div[1]/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/section/div[6]/div[3]/div/ul/li[6]/div[1]/div[1]</value>
   </webElementProperties>
</WebElementEntity>
