<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Click_13_Kartu_KreditCicilan</name>
   <tag></tag>
   <elementGuidId>3f404d26-3a14-4ae8-8c96-9ba8dadd5c1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/section/div[6]/div[3]/div/ul/li[16]/div[1]/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/section/div[6]/div[3]/div/ul/li[16]/div[1]/div[1]</value>
   </webElementProperties>
</WebElementEntity>
