<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Blanja_Sekarang</name>
   <tag></tag>
   <elementGuidId>7cd17363-6c8f-4c8d-82e8-703666e5b18d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;pulsa&quot;]/div/div[1]/div[3]/div/form/div[7]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;pulsa&quot;]/div/div[1]/div[3]/div/form/div[7]/input</value>
   </webElementProperties>
</WebElementEntity>
