<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Nominal1</name>
   <tag></tag>
   <elementGuidId>7b61e5de-50f0-416d-be4c-546b73a9adb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;pulsa&quot;]/div/div[1]/div[3]/div/form/div[2]/ul/li[8]/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;pulsa&quot;]/div/div[1]/div[3]/div/form/div[2]/ul/li[8]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
